# Generated by Django 5.2.14 on 2026-07-06 19:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_cancelled_at_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'دفعة', 'verbose_name_plural': 'المدفوعات'},
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ تأكيد استلام الدفع', null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text='وصف الدفعة (سبب الدفع، ملاحظات)', verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='تاريخ استحقاق الدفع', null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='تاريخ ووقت الدفع الفعلي', verbose_name='تاريخ الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('credit_card', 'بطاقة ائتمان'), ('debit_card', 'بطاقة خصم'), ('cheque', 'شيك'), ('mobile', 'محفظة إلكترونية'), ('online', 'دفع إلكتروني'), ('other', 'أخرى')], db_index=True, default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='رفع صورة الإيصال أو إثبات الدفع', null=True, upload_to='receipts/payments/%Y/%m/', verbose_name='إيصال الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='رقم المرجع من البنك أو المعاملة', max_length=100, verbose_name='رقم المرجع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ استرداد المبلغ', null=True, verbose_name='تاريخ الاسترداد'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('failed', 'فشل'), ('refunded', 'مسترد'), ('partial', 'مدفوع جزئياً')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='رقم المعاملة من بوابة الدفع', max_length=100, verbose_name='رقم المعاملة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ المدفوع', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='الحجز'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'دفعة مقدمة'), ('installment', 'قسط'), ('full', 'دفعة كاملة'), ('extra', 'دفعة إضافية'), ('remaining', 'المتبقي')], db_index=True, max_length=20, verbose_name='نوع الدفعة'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'status'], name='payments_pa_payment_05904b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
    ]
