# Generated by Django 5.2.14 on 2026-07-06 19:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_cancelled_at_and_more'),
        ('customers', '0002_alter_customer_options_customer_address_and_more'),
        ('finance', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-income_date', '-created_at'], 'verbose_name': 'إيراد', 'verbose_name_plural': 'الإيرادات'},
        ),
        migrations.AddField(
            model_name='expense',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bookings.booking', verbose_name='الحجز'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للمصروف', verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, help_text='تاريخ استحقاق الدفع (للفواتير)', null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='تاريخ حدوث المصروف', verbose_name='تاريخ المصروف'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('credit', 'بطاقة ائتمان'), ('cheque', 'شيك'), ('other', 'أخرى')], db_index=True, default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='reports.report', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, help_text='رفع صورة الإيصال (PDF أو صورة)', null=True, upload_to='receipts/expenses/%Y/%m/', verbose_name='إيصال'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='رقم الإيصال من المورد', max_length=50, verbose_name='رقم الإيصال'),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, help_text='اسم المورد أو الشخص المستحق', max_length=200, verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف المورد'),
        ),
        migrations.AddField(
            model_name='income',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='bookings.booking', verbose_name='الحجز'),
        ),
        migrations.AddField(
            model_name='income',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AddField(
            model_name='income',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='customers.customer', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للإيراد', verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الإيراد'),
        ),
        migrations.AddField(
            model_name='income',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='ملف الفاتورة'),
        ),
        migrations.AddField(
            model_name='income',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='رقم الفاتورة الصادر', max_length=50, verbose_name='رقم الفاتورة'),
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('credit', 'بطاقة ائتمان'), ('cheque', 'شيك'), ('online', 'دفع إلكتروني'), ('other', 'أخرى')], db_index=True, default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='reports.report', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('booking', 'حجز تصوير'), ('package', 'باقة تصوير'), ('print', 'مطبوعات'), ('digital', 'ملفات رقمية'), ('album', 'ألبوم صور'), ('framing', 'تأطير'), ('studio_rent', 'تأجير استوديو'), ('workshop', 'ورشة عمل'), ('other', 'أخرى')], db_index=True, default='booking', max_length=50, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(blank=True, help_text='عنوان الإيراد (يُملأ تلقائياً من الحجز إن لم يُحدد)', max_length=200, verbose_name='عنوان الإيراد'),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ بالعملة المحلية', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('equipment', 'معدات'), ('salary', 'رواتب'), ('rent', 'إيجار'), ('utilities', 'مرافق'), ('marketing', 'تسويق'), ('software', 'برمجيات'), ('maintenance', 'صيانة'), ('travel', 'سفر'), ('supplies', 'لوازم'), ('tax', 'ضرائب'), ('other', 'أخرى')], db_index=True, max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='عنوان المصروف'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ بالعملة المحلية', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='finance_exp_categor_095875_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'expense_date'], name='finance_exp_status_e3e75d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'status'], name='finance_exp_project_fe2a40_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['source', 'income_date'], name='finance_inc_source_de116c_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['booking', 'source'], name='finance_inc_booking_083d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['customer', 'income_date'], name='finance_inc_custome_f2c90b_idx'),
        ),
    ]
