# Generated by Django 5.2.14 on 2026-07-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الباقة')),
                ('category', models.CharField(choices=[('wedding', 'زفاف'), ('birthday', 'عيد ميلاد'), ('event', 'مناسبات'), ('studio', 'استوديو')], max_length=20, verbose_name='نوع الباقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_hours', models.PositiveIntegerField(default=1, verbose_name='عدد الساعات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'ordering': ['-created_at'],
            },
        ),
    ]
