# Generated by Django 5.2.14 on 2026-07-06 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('booking', 'تقرير حجوزات'), ('financial', 'تقرير مالي'), ('customer', 'تقرير عملاء'), ('photographer', 'تقرير مصورين'), ('payment', 'تقرير مدفوعات'), ('expense', 'تقرير مصروفات'), ('profit', 'تقرير أرباح'), ('daily', 'تقرير يومي'), ('weekly', 'تقرير أسبوعي'), ('monthly', 'تقرير شهري'), ('yearly', 'تقرير سنوي'), ('custom', 'تقرير مخصص')], db_index=True, max_length=20, verbose_name='نوع التقرير')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='صيغة التقرير')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('processing', 'جاري التجهيز'), ('completed', 'مكتمل'), ('failed', 'فشل')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='فلاتر إضافية للتقرير (مثل: photographer_id, customer_id, status)', verbose_name='الفلاتر')),
                ('data', models.JSONField(blank=True, default=dict, help_text='بيانات التقرير المستخرجة', verbose_name='البيانات')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='ملخص التقرير (إجمالي، متوسط، عدد...)', verbose_name='الملخص')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='ملف التقرير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='التكرار')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=الأحد, 1=الاثنين, ...', null=True, verbose_name='يوم الأسبوع')),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-31', null=True, verbose_name='يوم الشهر')),
                ('time', models.TimeField(default='09:00', verbose_name='الوقت')),
                ('recipients', models.JSONField(default=list, help_text='قائمة البريد الإلكتروني للمستلمين', verbose_name='المستلمين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل القادم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report')),
            ],
            options={
                'verbose_name': 'جدول تقرير',
                'verbose_name_plural': 'جداول التقارير',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم القالب')),
                ('report_type', models.CharField(choices=[('booking', 'تقرير حجوزات'), ('financial', 'تقرير مالي'), ('customer', 'تقرير عملاء'), ('photographer', 'تقرير مصورين'), ('payment', 'تقرير مدفوعات'), ('expense', 'تقرير مصروفات'), ('profit', 'تقرير أرباح'), ('daily', 'تقرير يومي'), ('weekly', 'تقرير أسبوعي'), ('monthly', 'تقرير شهري'), ('yearly', 'تقرير سنوي'), ('custom', 'تقرير مخصص')], max_length=20, verbose_name='نوع التقرير')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('config', models.JSONField(default=dict, help_text='إعدادات التقرير (أعمدة، تنسيق، فلاتر افتراضية)', verbose_name='إعدادات القالب')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قالب تقرير',
                'verbose_name_plural': 'قوالب التقارير',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', 'generated_at'], name='reports_rep_created_99fdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx'),
        ),
    ]
