# Generated by Django 5.2.14 on 2026-07-06 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='blacklist_reason',
            field=models.TextField(blank=True, help_text='سبب حظر العميل إن وجد', verbose_name='سبب الحظر'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default='مصر', max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'عميل عادي'), ('vip', 'عميل VIP'), ('corporate', 'شركة / مؤسسة'), ('agency', 'وكالة / استوديو')], db_index=True, default='regular', max_length=20, verbose_name='نوع العميل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='customer',
            name='facebook',
            field=models.URLField(blank=True, help_text='رابط حساب Facebook', null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى'), ('other', 'آخر')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='customer',
            name='instagram',
            field=models.URLField(blank=True, help_text='رابط حساب Instagram', null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(db_index=True, default=False, help_text='تعطيل العميل ومنعه من الحجز', verbose_name='محظور'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_booking_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر حجز'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات إضافية عن العميل', verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'هاتف'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية')], default='phone', max_length=20, verbose_name='طريقة التواصل المفضلة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_customers', to='packages.package', verbose_name='الباقة المفضلة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to=settings.AUTH_USER_MODEL, verbose_name='المصور المفضل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الحجوزات'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات'),
        ),
        migrations.AddField(
            model_name='customer',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter / X'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='البريد الإلكتروني للعميل (اختياري)', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, help_text='أدخل رقم الهاتف مع مفتاح الدولة (مثال: +201234567890)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون صحيحاً (مثال: 0123456789 أو +201234567890)', regex='^\\+?[0-9]{10,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'phone'], name='customers_c_name_ae0c34_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', 'is_active'], name='customers_c_custome_5cafca_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx'),
        ),
    ]
