# Generated by Django 5.2.14 on 2026-07-07 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='البريد الإلكتروني للعميل (اختياري)', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='البريد الإلكتروني'),
        ),
    ]
